# fly.toml app configuration file generated for spring-surf-4417 on 2023-05-11T01:14:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-surf-4417"
primary_region = "nrt"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_URL = "https://spring-surf-4417.fly.dev"
  APP_NAME = "Laravel"
  APP_DEBUG = false
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.lyayfszrlgubopihoqnj.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
